name: audiolab
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=24.0
  - setuptools=69.0.3
  - numpy=1.26.4
  - scipy=1.15.0
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - cudatoolkit=12.1
  - ffmpeg
  - pandas=2.2.3
  - matplotlib=3.10.0
  - protobuf=3.19.6
  - ninja
  - pip:
    - -r requirements-fixed.txt
    - mamba-ssm[causal-conv1d]
    - TTS
    - fairseq
    - whisperx
    - onnxruntime-gpu
    - ./wheels/audiosr-0.0.8-py2.py3-none-any.whl 